name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Linux 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: anaconda, conda-forge
    - run: conda install -y -c conda-forge constructor
    - run: mkdir build
    - run: constructor -v --output-dir=build --platform="linux-64" constructor
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release_0.3.10"
        release_name: Release 0.3.10
        draft: false
        prerelease: false

  build_mac:
    name: MacOsX
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: anaconda, conda-forge
    - run: conda install -y -c conda-forge constructor
    - run: mkdir build
    - run: constructor -v --output-dir=build --platform="osx-64" constructor
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release_0.3.10"
        release_name: Release 0.3.10
        draft: false
        prerelease: false

  build_win:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: anaconda, conda-forge
    - run: conda install -y -c conda-forge constructor
    - run: mkdir build
    - run: constructor -v --output-dir=build --platform="win-64" constructor
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release_0.3.10"
        release_name: Release 0.3.10
        draft: false
        prerelease: false
